apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv10 # Name
  namespace: nextcloud      # Namespace
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi            #  maximale Grösse
  accessModes:
    - ReadWriteOnce         # Kann schreiben
  persistentVolumeReclaimPolicy: Retain # kann mehrmals geclaimt werden
  hostPath:
    path: /home/vmadmin/nextcloud-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc10  #  Name des Volume-claim
  namespace: nextcloud    #  Namespace nextcloud
spec:
  storageClassName: ""
  volumeName: nextcloud-pv10
  accessModes:
    - ReadWriteOnce       #  Schreibrechte
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi        #  Grösse des Storage
